language: node_js
node_js:
  - '7'
script:
  - npm run clean
  - npm run build
  - npm run coverage
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
cache:
  directories:
  - node_modules
